#!/usr/bin/env sh

identifier='([[:alpha:]]|\.)[[:graph:]]+'
number='[[:digit:]]+'

echo "%include \"builtins/core.asm\""
echo "%include \"builtins/stack.asm\""
echo "%include \"builtins/arith.asm\""
echo "%include \"builtins/util.asm\""
echo "%include \"stdlib/util.asm\""
echo "%include \"stdlib/io.asm\""

echo "___header"

cat | sed 's/;.*//g' | tr -s '[:space:]' '\n' | sed -E \
-e 's/^\+$/___add/g' \
-e 's/^-$/___sub/g' \
-e 's/^\*$/___mul/g' \
-e 's/^\/$/___div/g' \
-e 's/^<<$/___lsh/g' \
-e 's/^>>$/___rsh/g' \
-e 's/^\+\+$/___inc/g' \
-e 's/^--$/___dec/g' \
\
-e 's/^&$/___band/g' \
-e 's/^\|$/___bor/g' \
-e 's/^\^$/___bxor/g' \
-e 's/^~$/___bnot/g' \
\
-e 's/^and$/___and/g' \
-e 's/^or$/___or/g' \
-e 's/^xor$/___xor/g' \
-e 's/^not$/___not/g' \
\
-e 's/^=$/___eq/g' \
-e 's/^!=$/___neq/g' \
-e 's/^<$/___lt/g' \
-e 's/^<=$/___lte/g' \
-e 's/^>$/___gt/g' \
-e 's/^>=$/___gte/g' \
\
-e 's/^\[$/___mark/g' \
-e 's/^\]$/___unmark/g' \
\
-e 's/^neg$/___neg/g' \
-e 's/^abs$/___abs/g' \
-e 's/^min$/___min/g' \
-e 's/^max$/___max/g' \
-e 's/^clear$/___clear/g' \
-e 's/^here$/___here/g' \
-e 's/^if$/___if/g' \
-e 's/^br$/___branch/g' \
-e 's/^#$/___count/g' \
-e 's/^\?$/___choose/g' \
-e 's/^\.$/___go/g' \
-e 's/^call$/___call_go/g' \
\
-e 's/^true$/___true/g' \
-e 's/^false$/___false/g' \
\
-e 's/^\|>$/___deque_pop/g' \
-e 's/^>\|$/___deque_push/g' \
\
-e 's/^set$/___set/g' \
-e 's/^get$/___get/g' \
-e 's/^mget$/___mget/g' \
-e 's/^mset$/___mset/g' \
-e 's/^pop$/___pop/g' \
-e 's/^swap$/___swap/g' \
-e 's/^dup$/___dup/g' \
-e 's/^over$/___over/g' \
-e 's/^nip$/___nip/g' \
-e 's/^tuck$/___tuck/g' \
-e 's/^rotl$/___rotl/g' \
-e 's/^rotr$/___rotr/g' \
\
-e "s/^($number)$/___push \1/g" \
-e "s/^&($identifier)$/___push \1/g" \
-e "s/^($identifier)$/___call \1/g" \
-e "s/^@($identifier)$/\1:/g"

