comment ::= ? ;.*$ ?
identifier ::= ? {XID_Start}{XID_Continue}* ?
number ::= ? [0-9]+ ? | ? 0x[0-9A-Fa-f]+ ?

workspace ::= '[' <instruction>* ']'
let ::= 'let' <identifier> <instruction>+
quote ::= '{' <instruction>+ '}'

instruction ::=
	<quote> | <let> | <workspace> | <identifier> |
	'+' | '-' | '*' | '/' | '%'

function ::= <instruction>* '::' <identifier>
program ::= ( <function> | <instruction> )*
