comment ::= ? ;.*$ ?
identifier ::= ? {XID_Start}{XID_Continue}* ?
number ::= ? [0-9]+ ? | ? 0x[0-9A-Fa-f]+ ?

call ::= '&' <identifier>
workspace ::= '[' <instruction>* ']'
label ::= '@' <identifier>

instruction ::=
	<workspace> | <label> | <identifier> | <call> |
	'+' | '-' | '*' | '/' | '%'

function ::= 'fn' <identifier> <instruction>*
program ::= ( <function> | <instruction> )*
