files: ^cdc/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-byte-order-marker

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
